spring:

  datasource:
    url: jdbc:mysql://localhost:3306/netology
    username: root
    password: mysql

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: password

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  location: /home/vvk

